In [1]:
!pip install stanza tqdm -q

Collecting stanza
  Downloading stanza-1.11.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/dist-packages (4.67.1)
Requirement already satisfied: emoji in /usr/local/lib/python3.11/dist-packages (from stanza) (2.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.11/dist-packages (from stanza) (1.26.4)
Requirement already satisfied: protobuf>=3.15.0 in /usr/local/lib/python3.11/dist-packages (from stanza) (6.33.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from stanza) (2.32.5)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from stanza) (3.5)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.11/dist-packages (from stanza) (2.6.0+cu124)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (4.15.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (2025.10.0)
Collecting nvidia-cuda-nvrtc-cu12==12.4.127 (from torch>=1.13.0->stanza)
  Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-runtime-cu12==12.4.127 (from torch>=1.13.0->stanza)
  Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cuda-cupti-cu12==12.4.127 (from torch>=1.13.0->stanza)
  Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cudnn-cu12==9.1.0.70 (from torch>=1.13.0->stanza)
  Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cublas-cu12==12.4.5.8 (from torch>=1.13.0->stanza)
  Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cufft-cu12==11.2.1.3 (from torch>=1.13.0->stanza)
  Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-curand-cu12==10.3.5.147 (from torch>=1.13.0->stanza)
  Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Collecting nvidia-cusolver-cu12==11.6.1.9 (from torch>=1.13.0->stanza)
  Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Collecting nvidia-cusparse-cu12==12.3.1.170 (from torch>=1.13.0->stanza)
  Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl.metadata (1.6 kB)
Requirement already satisfied: nvidia-cusparselt-cu12==0.6.2 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (0.6.2)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (12.4.127)
Collecting nvidia-nvjitlink-cu12==12.4.127 (from torch>=1.13.0->stanza)
  Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata (1.5 kB)
Requirement already satisfied: triton==3.2.0 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (3.2.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch>=1.13.0->stanza) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch>=1.13.0->stanza) (1.3.0)
Requirement already satisfied: mkl_fft in /usr/local/lib/python3.11/dist-packages (from numpy->stanza) (1.3.8)
Requirement already satisfied: mkl_random in /usr/local/lib/python3.11/dist-packages (from numpy->stanza) (1.2.4)
Requirement already satisfied: mkl_umath in /usr/local/lib/python3.11/dist-packages (from numpy->stanza) (0.1.1)
Requirement already satisfied: mkl in /usr/local/lib/python3.11/dist-packages (from numpy->stanza) (2025.3.0)
Requirement already satisfied: tbb4py in /usr/local/lib/python3.11/dist-packages (from numpy->stanza) (2022.3.0)
Requirement already satisfied: mkl-service in /usr/local/lib/python3.11/dist-packages (from numpy->stanza) (2.4.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->stanza) (2025.10.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch>=1.13.0->stanza) (3.0.3)
Requirement already satisfied: onemkl-license==2025.3.0 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->stanza) (2025.3.0)
Requirement already satisfied: intel-openmp<2026,>=2024 in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->stanza) (2024.2.0)
Requirement already satisfied: tbb==2022.* in /usr/local/lib/python3.11/dist-packages (from mkl->numpy->stanza) (2022.3.0)
Requirement already satisfied: tcmlib==1.* in /usr/local/lib/python3.11/dist-packages (from tbb==2022.*->mkl->numpy->stanza) (1.4.0)
Requirement already satisfied: intel-cmplr-lib-rt in /usr/local/lib/python3.11/dist-packages (from mkl_umath->numpy->stanza) (2024.2.0)
Requirement already satisfied: intel-cmplr-lib-ur==2024.2.0 in /usr/local/lib/python3.11/dist-packages (from intel-openmp<2026,>=2024->mkl->numpy->stanza) (2024.2.0)
Downloading stanza-1.11.0-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 20.5 MB/s eta 0:00:0000:010:01
Downloading nvidia_cublas_cu12-12.4.5.8-py3-none-manylinux2014_x86_64.whl (363.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 5.1 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_cupti_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (13.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 98.1 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (24.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 80.1 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (883 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 40.7 MB/s eta 0:00:00
Downloading nvidia_cudnn_cu12-9.1.0.70-py3-none-manylinux2014_x86_64.whl (664.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.7 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cufft_cu12-11.2.1.3-py3-none-manylinux2014_x86_64.whl (211.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 6.7 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_curand_cu12-10.3.5.147-py3-none-manylinux2014_x86_64.whl (56.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 33.4 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_cusolver_cu12-11.6.1.9-py3-none-manylinux2014_x86_64.whl (127.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 13.9 MB/s eta 0:00:0000:0100:01
Downloading nvidia_cusparse_cu12-12.3.1.170-py3-none-manylinux2014_x86_64.whl (207.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 2.1 MB/s eta 0:00:00:00:0100:01
Downloading nvidia_nvjitlink_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl (21.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 57.8 MB/s eta 0:00:0000:0100:01
Installing collected packages: nvidia-nvjitlink-cu12, nvidia-curand-cu12, nvidia-cufft-cu12, nvidia-cuda-runtime-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-cupti-cu12, nvidia-cublas-cu12, nvidia-cusparse-cu12, nvidia-cudnn-cu12, nvidia-cusolver-cu12, stanza
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlink-cu12-12.5.82
  Attempting uninstall: nvidia-curand-cu12
    Found existing installation: nvidia-curand-cu12 10.3.6.82
    Uninstalling nvidia-curand-cu12-10.3.6.82:
      Successfully uninstalled nvidia-curand-cu12-10.3.6.82
  Attempting uninstall: nvidia-cufft-cu12
    Found existing installation: nvidia-cufft-cu12 11.2.3.61
    Uninstalling nvidia-cufft-cu12-11.2.3.61:
      Successfully uninstalled nvidia-cufft-cu12-11.2.3.61
  Attempting uninstall: nvidia-cuda-runtime-cu12
    Found existing installation: nvidia-cuda-runtime-cu12 12.5.82
    Uninstalling nvidia-cuda-runtime-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-runtime-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-nvrtc-cu12
    Found existing installation: nvidia-cuda-nvrtc-cu12 12.5.82
    Uninstalling nvidia-cuda-nvrtc-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-nvrtc-cu12-12.5.82
  Attempting uninstall: nvidia-cuda-cupti-cu12
    Found existing installation: nvidia-cuda-cupti-cu12 12.5.82
    Uninstalling nvidia-cuda-cupti-cu12-12.5.82:
      Successfully uninstalled nvidia-cuda-cupti-cu12-12.5.82
  Attempting uninstall: nvidia-cublas-cu12
    Found existing installation: nvidia-cublas-cu12 12.5.3.2
    Uninstalling nvidia-cublas-cu12-12.5.3.2:
      Successfully uninstalled nvidia-cublas-cu12-12.5.3.2
  Attempting uninstall: nvidia-cusparse-cu12
    Found existing installation: nvidia-cusparse-cu12 12.5.1.3
    Uninstalling nvidia-cusparse-cu12-12.5.1.3:
      Successfully uninstalled nvidia-cusparse-cu12-12.5.1.3
  Attempting uninstall: nvidia-cudnn-cu12
    Found existing installation: nvidia-cudnn-cu12 9.3.0.75
    Uninstalling nvidia-cudnn-cu12-9.3.0.75:
      Successfully uninstalled nvidia-cudnn-cu12-9.3.0.75
  Attempting uninstall: nvidia-cusolver-cu12
    Found existing installation: nvidia-cusolver-cu12 11.6.3.83
    Uninstalling nvidia-cusolver-cu12-11.6.3.83:
      Successfully uninstalled nvidia-cusolver-cu12-11.6.3.83
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
libcugraph-cu12 25.6.0 requires libraft-cu12==25.6.*, but you have libraft-cu12 25.2.0 which is incompatible.
pylibcugraph-cu12 25.6.0 requires pylibraft-cu12==25.6.*, but you have pylibraft-cu12 25.2.0 which is incompatible.
pylibcugraph-cu12 25.6.0 requires rmm-cu12==25.6.*, but you have rmm-cu12 25.2.0 which is incompatible.
Successfully installed nvidia-cublas-cu12-12.4.5.8 nvidia-cuda-cupti-cu12-12.4.127 nvidia-cuda-nvrtc-cu12-12.4.127 nvidia-cuda-runtime-cu12-12.4.127 nvidia-cudnn-cu12-9.1.0.70 nvidia-cufft-cu12-11.2.1.3 nvidia-curand-cu12-10.3.5.147 nvidia-cusolver-cu12-11.6.1.9 nvidia-cusparse-cu12-12.3.1.170 nvidia-nvjitlink-cu12-12.4.127 stanza-1.11.0

In [2]:
import pandas as pd
from collections import Counter
from tqdm import tqdm
import stanza


# ---------- CONFIG ----------
PATH_CHUNKS = r"/kaggle/input/corpus-para-ner/chunks_etiquetados_binario.xlsx"

OUTPUT_RESULTS = r"/kaggle/working/"

# ---------- CARGAR DATOS ----------
chunks_etiquetados = pd.read_excel(PATH_CHUNKS)

In [3]:
chunks_etiquetados.head()

,chunk_id,id_doc,texto_chunk,Ciencias_ambientales_ingenieria,Ciencias_espacio,Ciencias_fisicas,Ciencias_Geografia_oceanografia,Ciencias_medicas,Ciencias_metereologia,Ciencias_naturales,...,Ciencias_tierra,Ciencia_Administracion_ciencia_investigacion,Ciencia_biologia,Ciencia_enfoque_cientifico,Ciencia_hidrologia,Ciencia_matematicas_estadistica,Ciencia_patologia,Ciencia_recursos_naturales,categorias_detectadas,etiqueta_ciencia
0,0,1,"La Coalición Colombia Partido Alianza Verde, P...",0.411230,0.368818,0.363447,0.354240,0.378154,0.343397,0.387251,...,0.392998,0.423331,0.337017,0.352550,0.328395,0.394268,0.393815,0.389038,"[('ninguna', 0)]",0
1,1,1,"al mismo tiempo lo exponen, en ciertas ocasion...",0.331604,0.304309,0.346682,0.315253,0.344347,0.323262,0.344607,...,0.318409,0.378231,0.317467,0.368125,0.306375,0.381964,0.337864,0.306510,"[('ninguna', 0)]",0
2,2,1,los acuerdos con las Farc. Anunció que no prom...,0.356805,0.311163,0.303825,0.287517,0.329738,0.290927,0.332603,...,0.292858,0.405040,0.291387,0.322885,0.297822,0.338846,0.294842,0.318955,"[('ninguna', 0)]",0
3,3,1,moratoria en la explotación tipo fracking. Y f...,0.435032,0.397881,0.372960,0.368983,0.415538,0.357000,0.410173,...,0.392092,0.445708,0.370653,0.367256,0.341832,0.404120,0.375238,0.397525,"[('ninguna', 0)]",0
4,0,2,Las interpretaciones de la historia sirven com...,0.352643,0.367811,0.375234,0.357391,0.368184,0.347770,0.392265,...,0.368177,0.428733,0.353389,0.405911,0.371109,0.412153,0.397781,0.339795,"[('ninguna', 0)]",0

In [4]:
# --- Filtrar el dataframe original ---
df_filtrado = chunks_etiquetados[['chunk_id', 'id_doc', 'texto_chunk', 
                                  'categorias_detectadas', 'etiqueta_ciencia']].copy()

In [5]:
# --- Inicializar el pipeline de Stanza ---
nlp_stanza = stanza.Pipeline(
    lang="es",
    processors="tokenize,pos,lemma",
    use_gpu=True  # o False si no tienes GPU
)

2026-01-22 08:28:32 INFO: Checking for updates to resources.json in case models have been updated.  Note: this behavior can be turned off with download_method=None or download_method=DownloadMethod.REUSE_RESOURCES

Downloading https://raw.githubusercontent.com/stanfordnlp/stanza-resources/main/resources_1.11.0.json:   0%|  …

2026-01-22 08:28:32 INFO: Downloaded file to /root/stanza_resources/resources.json
2026-01-22 08:28:32 WARNING: Language es package default expects mwt, which has been added

Downloading https://huggingface.co/stanfordnlp/stanza-es/resolve/v1.11.0/models/tokenize/combined.pt:   0%|   …

Downloading https://huggingface.co/stanfordnlp/stanza-es/resolve/v1.11.0/models/mwt/combined.pt:   0%|        …

Downloading https://huggingface.co/stanfordnlp/stanza-es/resolve/v1.11.0/models/pos/combined_charlm.pt:   0%| …

Downloading https://huggingface.co/stanfordnlp/stanza-es/resolve/v1.11.0/models/lemma/combined_nocharlm.pt:   …

Downloading https://huggingface.co/stanfordnlp/stanza-es/resolve/v1.11.0/models/pretrain/conll17.pt:   0%|    …

Downloading https://huggingface.co/stanfordnlp/stanza-es/resolve/v1.11.0/models/forward_charlm/newswiki.pt:   …

Downloading https://huggingface.co/stanfordnlp/stanza-es/resolve/v1.11.0/models/backward_charlm/newswiki.pt:  …

2026-01-22 08:28:40 INFO: Loading these models for language: es (Spanish):
=================================
| Processor | Package           |
---------------------------------
| tokenize  | combined          |
| mwt       | combined          |
| pos       | combined_charlm   |
| lemma     | combined_nocharlm |
=================================

2026-01-22 08:28:40 INFO: Using device: cuda
2026-01-22 08:28:40 INFO: Loading: tokenize
2026-01-22 08:28:45 INFO: Loading: mwt
2026-01-22 08:28:45 INFO: Loading: pos
2026-01-22 08:28:47 INFO: Loading: lemma
2026-01-22 08:28:48 INFO: Done loading processors!

# Extraer frecuencias de POS a los textos

In [6]:
def extraer_pos_frecuencias_stanza(textos):
    """
    Procesa una lista de textos con Stanza y devuelve tres listas de diccionarios:
      - verbos_frec[i]: {lema: frecuencia}
      - adjetivos_frec[i]: {lema: frecuencia}
      - sustantivos_frec[i]: {lema: frecuencia}
    """
    verbos_frec, adjetivos_frec, sustantivos_frec = [], [], []

    for texto in tqdm(textos, desc="Procesando con Stanza"):
        try:
            if not isinstance(texto, str) or not texto.strip():
                verbos_frec.append({})
                adjetivos_frec.append({})
                sustantivos_frec.append({})
                continue
                
            doc = nlp_stanza(texto)
            verbos, adjetivos, sustantivos = [], [], []

            for sent in doc.sentences:
                for w in sent.words:
                    if not w.lemma.isalpha():
                        continue
                    if w.upos == "VERB":
                        verbos.append(w.lemma.lower())
                    elif w.upos == "ADJ":
                        adjetivos.append(w.lemma.lower())
                    elif w.upos == "NOUN":
                        sustantivos.append(w.lemma.lower())

            verbos_frec.append(dict(Counter(verbos)))
            adjetivos_frec.append(dict(Counter(adjetivos)))
            sustantivos_frec.append(dict(Counter(sustantivos)))

        except Exception as e:
            print(f"Error procesando texto: {e}")
            verbos_frec.append({})
            adjetivos_frec.append({})
            sustantivos_frec.append({})

    return verbos_frec, adjetivos_frec, sustantivos_frec

In [14]:
# --- Obtener listas de frecuencias ---
textos = df_filtrado['texto_chunk'].tolist()
verbos_frec, adjetivos_frec, sustantivos_frec = extraer_pos_frecuencias_stanza(textos)

# --- Crear DataFrames separados para cada categoría gramatical ---

# DataFrame para verbos
df_verbos = df_filtrado.copy()
df_verbos['verbos_lemas_frecuencias'] = verbos_frec
df_verbos.to_excel('verbos_stanza.xlsx', index=False)

Procesando con Stanza: 100%|██████████| 62651/62651 [3:05:33<00:00,  5.63it/s]

In [17]:
# DataFrame para adjetivos
df_adjetivos = df_filtrado.copy()
df_adjetivos['adjetivos_lemas_frecuencias'] = adjetivos_frec
df_adjetivos.to_excel('adjetivos_stanza.xlsx', index=False)

In [18]:
# DataFrame para sustantivos
df_sustantivos = df_filtrado.copy()
df_sustantivos['sustantivos_lemas_frecuencias'] = sustantivos_frec
df_sustantivos.to_excel('sustantivos_stanza.xlsx', index=False)

# Analizar frecuencias

In [15]:
PATH_WORKING = "/kaggle/working/"

df_verbos = pd.read_excel(PATH_WORKING + "verbos_stanza.xlsx")
df_adjetivos = pd.read_excel(PATH_WORKING + "adjetivos_stanza.xlsx")
df_sustantivos = pd.read_excel(PATH_WORKING + "sustantivos_stanza.xlsx")

df_verbos

,chunk_id,id_doc,texto_chunk,categorias_detectadas,etiqueta_ciencia,verbos_lemas_frecuencias
0,0,1,"La Coalición Colombia Partido Alianza Verde, P...","[('ninguna', 0)]",0,"{'presentar': 2, 'diagnosticar': 1, 'tener': 1..."
1,1,1,"al mismo tiempo lo exponen, en ciertas ocasion...","[('ninguna', 0)]",0,"{'exponer': 1, 'presentar': 1, 'ver': 1, 'tene..."
2,2,1,los acuerdos con las Farc. Anunció que no prom...,"[('ninguna', 0)]",0,"{'anunciar': 1, 'prometer': 2, 'decir': 2, 'pr..."
3,3,1,moratoria en la explotación tipo fracking. Y f...,"[('ninguna', 0)]",0,"{'mostrar': 1, 'decir': 1, 'faltar': 1, 'tener..."
4,0,2,Las interpretaciones de la historia sirven com...,"[('ninguna', 0)]",0,"{'servir': 1, 'haber': 1, 'comprender': 1, 'ci..."
...,...,...,...,...,...,...
62646,7,13676,"así, encuentra el 90 del alimento que guardó. ...","[('ninguna', 0)]",0,"{'encontrar': 1, 'guardar': 1, 'decir': 1, 'te..."
62647,8,13676,capacidad de predecir un evento futuro. Por lo...,"[('Ciencias_naturales', 0.48311546444892883)]",1,"{'predecir': 1, 'parecer': 3, 'cumplir': 1, 'r..."
62648,9,13676,similar. Se ha encontrado que éstos le roban l...,"[('ninguna', 0)]",0,"{'encontrar': 1, 'robar': 1, 'dejar': 1, 'acer..."
62649,10,13676,está siendo parcialmente validada con experime...,"[('Ciencias_naturales', 0.5003376007080078)]",1,"{'poner': 1, 'colgar': 1, 'encontrar': 1, 'con..."
62650,11,13676,amo? ¿Son esas también formas de representació...,"[('ninguna', 0)]",0,"{'amar': 2, 'decir': 3, 'indicar': 1, 'hacer':..."

In [19]:
import ast

def asegurar_dict(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str):
        try:
            return ast.literal_eval(x)
        except:
            return {}
    return {}

def construir_tabla_frecuencias(
    df,
    columna_diccionarios,
    columna_ciencia="etiqueta_ciencia"
):
    freq_total = Counter()
    freq_ciencia = Counter()

    for _, row in tqdm(df.iterrows(), total=len(df)):
        dic = asegurar_dict(row[columna_diccionarios])

        if not dic:
            continue

        freq_total.update(dic)

        if row[columna_ciencia] == 1:
            freq_ciencia.update(dic)

    # construir tabla
    data = []
    for palabra, f_total in freq_total.items():
        f_ciencia = freq_ciencia.get(palabra, 0)
        proporcion = f_ciencia / f_total if f_total > 0 else 0

        data.append({
            "palabra": palabra,
            "frecuencia_total": f_total,
            "frecuencia_ciencia": f_ciencia,
            "proporcion_ciencia": proporcion
        })

    df_resultado = pd.DataFrame(data)

    # protección contra DataFrame vacío
    if df_resultado.empty:
        print("⚠️ Advertencia: no se generaron frecuencias.")
        return df_resultado

    return df_resultado.sort_values(
        by="frecuencia_total",
        ascending=False
    ).reset_index(drop=True)

In [23]:
tabla_verbos = construir_tabla_frecuencias(
    df_verbos,
    columna_diccionarios="verbos_lemas_frecuencias"
)

tabla_adjetivos = construir_tabla_frecuencias(
    df_adjetivos,
    columna_diccionarios="adjetivos_lemas_frecuencias"
)

tabla_sustantivos = construir_tabla_frecuencias(
    df_sustantivos,
    columna_diccionarios="sustantivos_lemas_frecuencias"
)

100%|██████████| 62651/62651 [00:07<00:00, 8317.70it/s]
100%|██████████| 62651/62651 [00:06<00:00, 9304.73it/s]
100%|██████████| 62651/62651 [00:11<00:00, 5465.24it/s]

In [36]:
tabla_verbos[
        (tabla_verbos["frecuencia_ciencia"] >= 10) &
        (tabla_verbos["proporcion_ciencia"] >= 0.12)
    ].sort_values("frecuencia_ciencia", ascending=False)

         palabra  frecuencia_total  frecuencia_ciencia  proporcion_ciencia
25      permitir              5243                 799            0.152394
20        lograr              5865                 738            0.125831
45       generar              3460                 735            0.212428
26        buscar              5182                 713            0.137592
28         tomar              4935                 594            0.120365
...          ...               ...                 ...                 ...
1462    escasear                57                  10            0.175439
1795     devenir                39                  10            0.256410
1848   comiencer                37                  10            0.270270
2190  despliegar                26                  10            0.384615
1512     aquejar                54                  10            0.185185

[604 rows x 4 columns]

In [38]:
ruta_salida = "/kaggle/working/frecuencias_pos_global_vs_ciencia.xlsx"

with pd.ExcelWriter(ruta_salida) as writer:
    tabla_verbos.to_excel(
        writer,
        sheet_name="verbos",
        index=False
    )
    tabla_adjetivos.to_excel(
        writer,
        sheet_name="adjetivos",
        index=False
    )
    tabla_sustantivos.to_excel(
        writer,
        sheet_name="sustantivos",
        index=False
    )