In [1]:
import pandas as pd
import numpy as np

In [2]:
file_path = r"C:\Users\karen\Documents\HumanidadesDigitales_git\BDD_Corpus\Corpus_completo_revisado.xlsx"
corpus_completo = pd.read_excel(file_path, engine='openpyxl')

In [3]:
# Formatear fechas

meses = {
    'enero': '01',
    'febrero': '02',
    'marzo': '03',
    'abril': '04',
    'mayo': '05',
    'junio': '06',
    'julio': '07',
    'agosto': '08',
    'septiembre': '09',
    'octubre': '10',
    'noviembre': '11',
    'diciembre': '12'
}

def convertir_fecha(fecha_str):
    partes = fecha_str.split(' de ')
    dia = partes[0].zfill(2)  # Asegura 2 dígitos para días 1-9
    mes = meses[partes[1]]
    año = partes[2]
    return f"{dia}/{mes}/{año}"  # Formato DD/MM/AAAA

corpus_completo['Fecha'] = corpus_completo['Fecha'].apply(convertir_fecha)
corpus_completo['Fecha'] = pd.to_datetime(corpus_completo['Fecha'], format='%d/%m/%Y', errors='coerce')

In [4]:
corpus_completo

,Diario,Autor,Fecha,Título,Texto,Vínculo,ID
0,El Espectador,Gonzalo Hernández,2018-01-01,Fajardo: para nada tibio,"La Coalición Colombia –Partido Alianza Verde, ...",https://web.archive.org/web/20180102104221/htt...,1
1,El Espectador,Eduardo Barajas Sandoval,2018-01-01,Macedonia de Norte,Las interpretaciones de la historia sirven com...,https://web.archive.org/web/20180102104221/htt...,2
2,El Espectador,Daniel Emilio Rojas Castro,2018-01-01,El nacionalismo según Vargas Llosa,La semana pasada Mario Vargas Llosa publicó un...,https://web.archive.org/web/20180102104221/htt...,3
3,El Espectador,Reinaldo Spitaletta,2018-01-01,"Tiempo sagrado, tiempo profano","Pudiera decirse, sin ser una verdad absoluta, ...",https://web.archive.org/web/20180102104221/htt...,4
4,El Espectador,Aura Lucía Mera,2018-01-01,La rebelión de los bueyes,Lo mejor del encierro de Las Ventas fueron los...,https://web.archive.org/web/20180102104221/htt...,5
...,...,...,...,...,...,...,...
13671,Semana,Gonzalo Sánchez,2019-06-04,Es hora de salir de la trampa,Colombia tiene que liberarse del debate sobre ...,https://web.archive.org/web/20190605212054/htt...,13672
13672,Semana,Álvaro Jiménez,2019-06-03,La semana de los propietarios,"Hemos avanzado mucho como país, para silenciar...",https://web.archive.org/web/20190605212117/htt...,13673
13673,Semana,Jairo Gómez,2019-06-03,"Presidente, deje el estrés a un lado y gobierne","No pretendo, ni más faltaba, diseñarle las pol...",https://web.archive.org/web/20190605212129/htt...,13674
13674,Semana,Ana María Ruiz,2019-06-03,Era el mejor oficio del mundo,El periodismo que olisquea y escarba la realid...,https://web.archive.org/web/20190605220917/htt...,13675
13675,Semana,Julián de Zubiría Samper,2019-06-03,¿Piensan los animales?,La pregunta de si los animales también piensan...,https://web.archive.org/web/20190605220937/htt...,13676

In [9]:
# Contar número de documentos por año
conteo_años = corpus_completo['Fecha'].dt.year.value_counts().sort_index().reset_index()
conteo_años

   Fecha  count
0   2018   5151
1   2019   4018
2   2020   4507

In [11]:
# Contar número de documentos por diario
conteo_diarios = corpus_completo['Diario'].value_counts().reset_index()
conteo_diarios.columns = ['Diario', 'Número de documentos']
conteo_diarios

          Diario  Número de documentos
0  El Espectador                 10509
1      El Tiempo                  1982
2         Semana                  1185

In [12]:
# Número de autores diferentes por diario
autores_por_diario = corpus_completo.groupby('Diario')['Autor'].nunique().reset_index()
autores_por_diario.columns = ['Diario', 'Número de autores diferentes']
autores_por_diario

          Diario  Número de autores diferentes
0  El Espectador                           264
1      El Tiempo                           249
2         Semana                           105

In [13]:
# Numero de autores diferentes por año
autores_por_año = corpus_completo.groupby(corpus_completo['Fecha'].dt.year)['Autor'].nunique().reset_index()
autores_por_año.columns = ['Año', 'Número de autores diferentes']
autores_por_año

    Año  Número de autores diferentes
0  2018                           380
1  2019                           399
2  2020                           319

In [16]:
# Total autores diferentes en el corpus
total_autores_diferentes = corpus_completo['Autor'].nunique()
total_autores_diferentes

594

In [19]:
# Cantidad de palabras por documento
Cantidad_palabras = corpus_completo['Texto'].apply(lambda x: len(str(x).split()))
Cantidad_palabras.sum()

8620835

In [25]:
Cantidad_palabras.mean()

630.3623135419714

In [22]:
# Cantidad de palabras diferentes en todo el corpus
palabras_diferentes = set()
for texto in corpus_completo['Texto']:
    palabras = str(texto).split()
    palabras_diferentes.update(palabras)
    
len(palabras_diferentes)

342988

# Topic Modeling Bertopic

In [28]:
%pip install bertopic tf-keras transformers -q

Note: you may need to restart the kernel to use updated packages.

In [31]:
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer
import torch
from transformers import AutoTokenizer, AutoModelForMaskedLM
from transformers import pipeline
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from spacy.lang.es.stop_words import STOP_WORDS

In [30]:
sentence_model = AutoTokenizer.from_pretrained("dccuchile/bert-base-spanish-wwm-uncased")

In [32]:
topic_model = BERTopic(language="spanish",
    top_n_words=10,          # Palabras por tópico
    min_topic_size=20,       # Tamaño mínimo del cluster
    nr_topics=50,        # Número de tópicos
    calculate_probabilities=True,
    vectorizer_model=TfidfVectorizer(stop_words=list(STOP_WORDS)),
    embedding_model= sentence_model 
    )

In [33]:
texto_seleccionado = corpus_completo['Texto'].astype(str).tolist()
#texto_seleccionado = columnas_procesadas

CORRER = True
if CORRER:
    topics, probs = topic_model.fit_transform(texto_seleccionado)

In [37]:
topic_info

,Topic,Count,Name,Representation,Representative_Docs
0,-1,7796,-1_país_colombia_gobierno_años,"[país, colombia, gobierno, años, política, pre...",[No sería inexacto decir que uno de los factor...
1,0,578,0_presidente_trump_duque_gobierno,"[presidente, trump, duque, gobierno, biden, pa...",[Hacer análisis mesurados sobre los primeros 1...
2,1,509,1_virus_coronavirus_pandemia_covid,"[virus, coronavirus, pandemia, covid, salud, 1...",[Luego de seis meses de aparición del coronavi...
3,2,454,2_vida_mundo_tola_amor,"[vida, mundo, tola, amor, pa, casa, tiempo, di...",[Desde hace 23 años hemos dedicado en el Insti...
4,3,408,3_colombia_país_política_gobierno,"[colombia, país, política, gobierno, político,...",[Puede que la voz de uno no altere nada. Me ne...
5,4,322,4_educación_universidad_estudiantes_universidades,"[educación, universidad, estudiantes, universi...",[En el año 1993 el expresidente César Gaviria ...
6,5,285,5_paz_farc_jep_guerra,"[paz, farc, jep, guerra, guerrilla, proceso, c...",[Hay actualmente en desarrollo una nueva amena...
7,6,249,6_fiscal_fiscalía_martínez_nhm,"[fiscal, fiscalía, martínez, nhm, odebrecht, d...",[Supongamos que el video en el que aparece Pet...
8,7,235,7_internet_digital_información_datos,"[internet, digital, información, datos, televi...",[Resulta difícil hacer seguimiento a la avalan...
9,8,228,8_fútbol_jugadores_gol_equipo,"[fútbol, jugadores, gol, equipo, goles, torneo...","[La economía devastada, las fuerzas de ocupaci..."
10,9,211,9_venezuela_maduro_guaidó_venezolano,"[venezuela, maduro, guaidó, venezolano, venezo...",[El mundo espera la caída del dictador Nicolás...
11,10,210,10_música_arte_musical_teatro,"[música, arte, musical, teatro, festival, arti...",[Según informaciones de prensa la capital del ...
12,11,184,11_bogotá_buses_ciudad_metro,"[bogotá, buses, ciudad, metro, peñalosa, trans...",[Hay que hacer bien las cuentas al definir la ...
13,12,177,12_libros_libro_poesía_poeta,"[libros, libro, poesía, poeta, verso, poemas, ...",[El verso libre no es tan libre. Por su falta ...
14,13,135,13_candidatos_electoral_vuelta_petro,"[candidatos, electoral, vuelta, petro, candida...",[A poco más de una semana de la primera vuelta...
15,14,135,14_corte_uribe_justicia_jep,"[corte, uribe, justicia, jep, judicial, magist...",[Una reciente condena judicial del Tribunal Ad...
16,15,119,15_petro_gustavo_fajardo_duque,"[petro, gustavo, fajardo, duque, uribe, vuelta...",[Hablemos a calzón quitado: tal como están las...
17,16,115,16_sexual_mujeres_feminismo_sexo,"[sexual, mujeres, feminismo, sexo, acoso, sexu...",[Este es otro de esos casos en que el acusado ...
18,17,94,17_foto_fotos_imágenes_fotografía,"[foto, fotos, imágenes, fotografía, imagen, fo...",[Un hombre bien parecido sonríe con pícara tim...
19,18,88,18_agropecuario_productores_rural_agua,"[agropecuario, productores, rural, agua, riego...","[Siempre que asisto a los foros agrícolas, not..."
20,19,85,19_cnmh_salim_historia_acevedo,"[cnmh, salim, historia, acevedo, memoria, negr...",[El pobre desempeño de Darío Acevedo como dire...
21,20,77,20_coca_cocaína_drogas_cultivos,"[coca, cocaína, drogas, cultivos, glifosato, m...","[Reacciones a mi columna anterior, “ Quemas, d..."
22,21,59,21_protesta_protestas_paro_manifestantes,"[protesta, protestas, paro, manifestantes, mar...",[Aunque el Gobierno está haciendo lo que ellos...
23,22,58,22_cocina_arroz_plato_cocinar,"[cocina, arroz, plato, cocinar, platos, chef, ...","[La olla está sobre el fogón, los comensales s..."
24,23,53,23_china_hong_kong_xi,"[china, hong, kong, xi, taiwán, chino, chinos,...",[Hace 40 años Colombia restableció relaciones ...
25,24,51,24_cultura_zimmer_social_vida,"[cultura, zimmer, social, vida, pandemia, soci...",[Estos Relatos de los oficios y los días bien ...
26,25,46,25_petróleo_economía_crecimiento_déficit,"[petróleo, economía, crecimiento, déficit, pro...",[La economía terminó el año dentro de la tende...
27,26,44,26_salario_colombia_mínimo_empresas,"[salario, colombia, mínimo, empresas, inversió...","[Recientemente, el Senado colombiano aprobó un..."
28,27,44,27_pensiones_fondos_colpensiones_pensional,"[pensiones, fondos, colpensiones, pensional, a...",[Las AFP insisten en el modelo chileno de poca...
29,28,43,28_bolsonaro_lula_brasil_brasileños,"[bolsonaro, lula, brasil, brasileños, pt, jair...",[Lo previsto: ganó Jair Bolsonaro y el 1ro. de...
30,29,40,29_climático_climática_calentamiento_emisiones,"[climático, climática, calentamiento, emisione...","[El Acuerdo de París, logrado en la COP21 en 2..."
31,30,37,30_chile_piñera_pinochet_chilenos,"[chile, piñera, pinochet, chilenos, democracia...",[Un titular del periódico Financial Times sobr...
32,31,36,31_hitler_fascismo_guerra_mussolini,"[hitler, fascismo, guerra, mussolini, alemania...","[Que Alemania, la nación que engendró el nazis..."
33,32,35,32_cuba_eln_castro_protocolo,"[cuba, eln, castro, protocolo, negociadores, c...",[El presidente Duque sabe muy bien lo que hace...
34,33,34,33_tequendama_palenque_basilio_río,"[tequendama, palenque, basilio, río, palenquer...",[El paisaje actual del Tequendama evidencia la...
35,34,34,34_tributaria_reforma_impuestos_empresas,"[tributaria, reforma, impuestos, empresas, fin...","[En su columna “Carrasquillavirus” , Vicky Dáv..."
36,35,33,35_animales_especies_fauna_animal,"[animales, especies, fauna, animal, mci, biodi...","[En su campaña a la presidencia, Duque prometi..."
37,36,32,36_violencia_ifex_crímenes_paz,"[violencia, ifex, crímenes, paz, mancuso, homi...",[No sorprendería un comunicado del Eln aclaran...
38,37,32,37_aborto_embarazo_abortos_mujeres,"[aborto, embarazo, abortos, mujeres, abortar, ...",[En Colombia somos inmensamente afortunadas po...
39,38,31,38_stakeholders_contabilidad_organizaciones_ne...,"[stakeholders, contabilidad, organizaciones, n...",[Mucho se ha discutido acerca de qué tan paral...
40,39,27,39_religión_religiones_dios_cristianismo,"[religión, religiones, dios, cristianismo, igl...",[Dos milenios han sido suficientes para compro...
41,40,26,40_facebook_analytica_zuckerberg_cambridge,"[facebook, analytica, zuckerberg, cambridge, u...",[El escándalo Cambridge Analytica confirma que...
42,41,26,41_irán_nuclear_iraní_jcpoa,"[irán, nuclear, iraní, jcpoa, siria, trump, nu...",[Uno de los interrogantes que plantea la inten...
43,42,25,42_brexit_ue_unión_europea,"[brexit, ue, unión, europea, europa, irlanda, ...",[Conminados por las circunstancias de una cris...
44,43,24,43_claudia_alcaldesa_sylvia_lópez,"[claudia, alcaldesa, sylvia, lópez, amo, votar...",[Se aproximan las elecciones y las encuestas p...
45,44,24,44_bolívar_guayana_libertador_angostura,"[bolívar, guayana, libertador, angostura, boya...",[Hace 200 años –el 15 de noviembre de 1819– mu...
46,45,23,45_santrich_narcotráfico_sasa_blandón,"[santrich, narcotráfico, sasa, blandón, sae, o...",[Esta es la historia de cuatro helicópteros y ...
47,46,23,46_medimás_eps_cafesalud_ips,"[medimás, eps, cafesalud, ips, salud, clínicas...",[La maniobra financiera mediante la cual Medim...
48,47,22,47_política_democracia_schulz_partidos,"[política, democracia, schulz, partidos, consu...",[No solo los partidos políticos hacen política...
49,48,20,48_aviación_avianca_aerolíneas_pasajeros,"[aviación, avianca, aerolíneas, pasajeros, aer...",[Gran parte del desarrollo económico del mundo...

In [40]:
import plotly.express as px

# Obtener información de tópicos
topic_info = topic_model.get_topic_info()

# Filtrar outliers (tópico -1)
topic_info_filtered = topic_info[topic_info['Topic'] != -1]


# Gráfico de barras interactivo
fig = px.bar(topic_info,
             x='Topic',
             y='Count',
             color='Name',
             hover_data=['Representation'],
             title='Distribución de Tópicos',
             labels={'Count': 'N° Columnas', 'Name': 'Palabras Clave'},
             height=600)
fig.update_layout(xaxis={'type': 'category'})
fig.show()